language: android

android:
  components:
    - android-16

    ## Extras
    - extra-google-m2repository
    - extra-android-m2repository

env:
    - ANDROID_HOME=/usr/local/android-sdk-linux

script:
    - cd app && mvn clean package

      
