language: android

android:
  components:
    ## Android 2.3.3 
    - androind-10

    ## Extras
    - extra-google-m2repository
    - extra-android-m2repository

script:
    - cd app && mvn clean package
